### ISSUE TITLE
Add registrant table mutations

### ISSUE THREAD

**Issue by jakelowen** [gpsimpact/open_voter_reg#2]
Database table 'registrants' has been established to hold all basic info required to complete federal form.

Next step is to write records to table via graphql mutations. I'm thinking about one mutation operation where all input fields are optional.  If the unique user ID field "hash" is included in the mutation AND that uuid is found - then the data provided via the mutation should update/overwrite any data on file.  However if that UUID is not found, it should create a new record with provided uuid. If no hash input is provided, default to generating a new UUID.

Every mutation should return the UUID/hash of the affected/created row as well as the current value of all fields of that row.  In this way you can very easily create new records OR update existing records with partial info (ideal for step by step form wizard style web forms).

Discussion:
* Do we need to add a db column to "lock" a record to prevent updating?
* Should we add a string column to record most recent update step? i.e. if the front end has 6 or 7 steps, maybe we should record that value here and thus track last known step.

**Comment by jrazmi** [comment]
RE Lock:  What are the circumstances that would require a lock?  Or is it possible that we would need a Lock timestamp?  i.e.  someone completes all of the info so maybe we lock them from making any changes for 48 hours?

I like the idea of storing last completed step.  In some ways you can get at the info from what columns have info, but it might be nice to have that step right there for quick reference.

**Comment by jakelowen** [comment]
excepting the issue of locks, this was addressed in https://github.com/gpsimpact/open_voter_reg/commit/729a9b7d9735bbe8f5f9b3565fac89d77ad3e24c

I'm going to close this and start another separate issues(s) with the update step and lock questions.
