### ISSUE TITLE
Erase all personally identifiable information as soon as registration is confirmed.

### ISSUE THREAD

**Issue by jakelowen** [gpsimpact/open_voter_reg#3]
All information collected by the registrant must be retained until such time as we can confirm a successful registration via KSSOS data. This will likely be done with monthly voter file pulls.

Once we can verify a registration was successful we should record the "text_registrant_id" of the voter and remove ALL p.i.i.   In that way our data retention is offloaded to public data sources.

The only possible exception perhaps is to maintain basic contact information:
* First Name
* Last Name
* Email
* Phone (if provided)

to facilitate future communication with the newly registered voter. Any concerns with retaining about 4 data points?

**Comment by KSVotes** [comment]
That's a good point -- I think the SOS keeps emails, but I don't think they include them in the voterfiles that I've seen. This seems good to me.
