### ISSUE TITLE
Identify desktop/non-touch users and push to mobile

### ISSUE THREAD

**Issue by KSVotes** [gpsimpact/open_voter_reg#8]
Could be a pop-up at the beginning of the session or wait until the signature page.

Could ask them for a cell number to text the link to finish their application.

**Comment by KunalKarnik** [comment]
I believe that a good way to go about this is to:
- Give out an alert at the very start of the process when the user is on a non-touch device.
- The User will be made aware that he/she will require access to a touch device to complete the signup process.
- Then we let him/her fill in the other information (we can have access to maximum data even if they drop out without completing the entire process)
- And ending the process with a signature link (tentatively) [I'm looking into other better options for signature authentication]

Any thoughts?

**Comment by jakelowen** [comment]
Every registrant is assigned a unique ID in uuid4 format i.e. "a64d16b2-fe61-4b8b-b180-1effa1e27928".  If we ask for telephone number and their consent to be sent text messages at beginning of process we could then text them a link to a mobile-first signature page at the right moment.

i.e. https://ksvotes.org/sign/a64d16b2-fe61-4b8b-b180-1effa1e27928 

As soon as they submit the mobile signature, we could then have the desktop application proceed on to the next (final?) step.  This realtime notification could be achieved through use of graphql subscription protocol.

I think its best that this signature view route be part of the react app and handled through the react router vs an express route.
